DROP TABLE IF EXISTS ASSET_DETAILS CASCADE;
DROP TABLE IF EXISTS ASSETS CASCADE;
DROP TABLE IF EXISTS HISTORICAL_ASSETS CASCADE;
DROP TABLE IF EXISTS TRANSACTIONS CASCADE;
DROP TABLE IF EXISTS TRANSACTIONS_STAGE CASCADE;
-- DROP TABLE IF EXISTS FLYWAY_SCHEMA_HISTORY CASCADE;
