CREATE TABLE ASSETS
(
    ASSET_ID         SERIAL         NOT NULL,
    ASSET_DETAILS_ID INT            NOT NULL,
    QUANTITY         NUMERIC(19, 6) NOT NULL,
    COURSE           NUMERIC(19, 6) NOT NULL,
    TOTAL_VALUE      NUMERIC(19, 6) NOT NULL,
    PRIMARY KEY (ASSET_ID),
    CONSTRAINT FK_ASSET_DETAILS_ID
        FOREIGN KEY (ASSET_DETAILS_ID)
            REFERENCES ASSET_DETAILS (ASSET_DETAILS_ID)
);