CREATE TABLE TRANSACTIONS
(
    TRANSACTIONS_ID       SERIAL         NOT NULL,
    ACTIVE_TRANSACTION_ID INT            NOT NULL,
    TRANSACTION_TYPE      VARCHAR(20)    NOT NULL,
    TICKER                VARCHAR(10)    NOT NULL,
    QUANTITY              NUMERIC(19, 6) NOT NULL,
    COURSE                NUMERIC(19, 6) NOT NULL,
    TOTAL_VALUE           NUMERIC(19, 6) NOT NULL,
    DATE_OF_TRANSACTION   DATE           NOT NULL,
    PRIMARY KEY (TRANSACTIONS_ID),
    CONSTRAINT FK_ACTIVE_TRANSACTION_ID
        FOREIGN KEY (ACTIVE_TRANSACTION_ID)
            REFERENCES ACTIVE_TRANSACTIONS (ACTIVE_TRANSACTION_ID)
);